name: Snyk Vulnerability Scan
on:
  workflow_dispatch:
# jobs:
#   security:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Run Snyk to check for vulnerabilities
#         uses: snyk/actions/gradle@master
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         with:
#           args: --severity-threshold=high --all-sub-projects

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          repository: deleonenriqueta/java-agent-api
          ref: main

      - name: Set Up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions/gradle@master
        with:
          args: --all-sub-projects --command=test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
